# Generated by Django 4.0.6 on 2022-08-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_poductmodel_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductmodel',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.usermodel'),
        ),
    ]
