# Generated by Django 4.0.6 on 2022-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_poductmodel_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductmodel',
            name='ProductImage',
            field=models.ImageField(max_length=254, null=True, upload_to='photos/'),
        ),
    ]
